spring:
  datasource:
    url: jdbc:postgresql://localhost:55432/portafolio_db
    username: portafolio_user
    password: portafolio123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true